### PR TITLE
Improve linemod2d clustering

### PR DESCRIPTION
**Pull request by RunqiuBao**
In linemod2D,
1. use _highest-score candidate first_ in linemod2D clustering, instead of merging everything inside cluster.
2. add critical direction in linemod2D clustering.

### CODE REVIEW

**Comment by jerasman** [comment]
@RunqiuBao typo "perpendiculr". Also, where are your new variables documented? I didn't see their description

**Comment by RunqiuBao** [comment]
Added docs and cleaned rotationalClustering.

**Comment by RunqiuBao** [comment]
notes:
(1) definition of long object by 5 is ambiguous.
(2) critical direction <- use a better name.
(3) should support thin plane object as well.

**Comment by RunqiuBao** [comment]
@jerasman 
Updated:
(0) `longAndNarrowThreshold` can be configured as a parameter when rendering template.
(1) change `criticalDirection` to `narrowDirection`
(2) support both long object and thin plane object.

**Pull request closed without merging**
